BEGIN TRANSACTION;

-- BETA ARBUTIN (Active Ingredient - Category 1)
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Beta Arbutin', 'Arbutin', '497-76-7', 1, 7617.20, 'in_stock', 'kg', 1.0, 7.0, 'Store in cool, dry place. Temperature 15-25C. Protect from light.', 24, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Beta Arbutin'), '207-850-3', '74362', 'C12H16O7', 1, 1, 'EU restricted to max 7% in facial creams. Hydroquinone contamination must be below 1ppm. Natural source: bearberry plant.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Beta Arbutin'), 'White to off-white crystalline powder', 'Water-soluble up to 7%. Stable in ethanol and water.', 'Add to water phase. pH range 3-8, optimal stability at pH 6-7. Inhibits tyrosinase enzyme. May hydrolyze to hydroquinone in solution.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Beta Arbutin'), 'Brightening serums, dark spot treatments, melasma creams, anti-pigmentation products', 'Skin brightening, reduces hyperpigmentation, fades dark spots, inhibits melanin production, safer alternative to hydroquinone');

-- VITAMIN E (Additive - Category 2)
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Vitamin E', 'Tocopherol', '59-02-9', 2, 1919.15, 'in_stock', 'kg', 0.2, 5.0, 'Store in cool, dark place. Temperature 15-25C. Protect from light and air.', 24, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Vitamin E'), '200-412-2', '80273', 'C29H50O2', 1, 1, 'Generally safe. Well-tolerated. May cause redness on very sensitive skin. Patch test recommended.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Vitamin E'), 'Pale yellow viscous liquid', 'Oil-soluble. Insoluble in water.', 'Add to oil phase or at cool-down. Antioxidant for oils - prevents rancidity. Use 0.2% for preservation, up to 5% for skin benefits. Heat sensitive.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Vitamin E'), 'Anti-aging creams, moisturizers, sunscreens, lip balms, hair care, oil stabilization', 'Antioxidant, UV protection, anti-aging, moisturizing, prevents oil rancidity, skin healing, improves skin texture');

COMMIT;
