BEGIN TRANSACTION;
UPDATE ingredients SET landed_cost_net_gst = 7000.0 WHERE name = 'Hyaluronic Acid (5M Hyaskin)';
UPDATE ingredients SET landed_cost_net_gst = 8350.24 WHERE name = 'Ajidew ZN-100';
UPDATE ingredients SET landed_cost_net_gst = 9000.0 WHERE name = 'Alpha Arbutin';
UPDATE ingredients SET landed_cost_net_gst = 500.0 WHERE name = 'Banana Spray Dried Powder';
UPDATE ingredients SET landed_cost_net_gst = 297.22 WHERE name = 'Charcoal Powder';
UPDATE ingredients SET landed_cost_net_gst = 7776.08 WHERE name = 'Derma White WF';
UPDATE ingredients SET landed_cost_net_gst = 2115.0 WHERE name = 'Eutanol G';
UPDATE ingredients SET landed_cost_net_gst = 1850.0 WHERE name = 'Kojic Acid';
UPDATE ingredients SET landed_cost_net_gst = 2250.04 WHERE name = 'Kojic Acid Dipalmitate';
UPDATE ingredients SET landed_cost_net_gst = 17003.53 WHERE name = 'L-Glutathione Reduced';
UPDATE ingredients SET landed_cost_net_gst = 8700.0 WHERE name = 'Ceramide Complex (Oli-8106)';
UPDATE ingredients SET landed_cost_net_gst = 1000.0 WHERE name = 'Salicylic Acid';
UPDATE ingredients SET landed_cost_net_gst = 350.0 WHERE name = 'Titanium Dioxide';
UPDATE ingredients SET landed_cost_net_gst = 450.0 WHERE name = 'Tomato Spray Dried Powder';
UPDATE ingredients SET landed_cost_net_gst = 8800.0 WHERE name = 'Veg Collagen';
UPDATE ingredients SET landed_cost_net_gst = 290.0 WHERE name = 'Zinc Oxide';
UPDATE ingredients SET landed_cost_net_gst = 126.72 WHERE name = 'AOS';
UPDATE ingredients SET landed_cost_net_gst = 245.0 WHERE name = 'Bees Wax';
UPDATE ingredients SET landed_cost_net_gst = 295.0 WHERE name = 'Beta Cyclodextrin';
UPDATE ingredients SET landed_cost_net_gst = 450.0 WHERE name = 'BHT (Butylated Hydroxytoluene)';
UPDATE ingredients SET landed_cost_net_gst = 700.0 WHERE name = 'Bronopol';
UPDATE ingredients SET landed_cost_net_gst = 1000.0 WHERE name = 'Carrageenan Powder';
UPDATE ingredients SET landed_cost_net_gst = 287.22 WHERE name = 'EDTA';
UPDATE ingredients SET landed_cost_net_gst = 1500.0 WHERE name = 'Galguard Trident';
UPDATE ingredients SET landed_cost_net_gst = 162.0 WHERE name = 'HCO';
UPDATE ingredients SET landed_cost_net_gst = 574.7 WHERE name = 'Lanolin';
UPDATE ingredients SET landed_cost_net_gst = 75.0 WHERE name = 'Magnesium Chloride';
UPDATE ingredients SET landed_cost_net_gst = 55.0 WHERE name = 'Magnesium Sulphate';
UPDATE ingredients SET landed_cost_net_gst = 46.0 WHERE name = 'Maize Starch Powder';
UPDATE ingredients SET landed_cost_net_gst = 95.0 WHERE name = 'Microcrystalline Cellulose';
UPDATE ingredients SET landed_cost_net_gst = 585.53 WHERE name = 'Niacinamide';
UPDATE ingredients SET landed_cost_net_gst = 1050.0 WHERE name = 'Olivem 300';
UPDATE ingredients SET landed_cost_net_gst = 760.22 WHERE name = 'Olivem 400';
UPDATE ingredients SET landed_cost_net_gst = 133.61 WHERE name = 'Glycerin';
UPDATE ingredients SET landed_cost_net_gst = 60.0 WHERE name = 'SBC';
UPDATE ingredients SET landed_cost_net_gst = 4200.0 WHERE name = 'Sodium Ascorbyl Phosphate';
UPDATE ingredients SET landed_cost_net_gst = 110.0 WHERE name = 'Sodium Citrate';
UPDATE ingredients SET landed_cost_net_gst = 385.0 WHERE name = 'Sodium CMC';
UPDATE ingredients SET landed_cost_net_gst = 205.67 WHERE name = 'Sodium Lactate';
UPDATE ingredients SET landed_cost_net_gst = 78.6 WHERE name = 'Sodium Metabisulphite';
UPDATE ingredients SET landed_cost_net_gst = 500.0 WHERE name = 'Sodium PCA';
UPDATE ingredients SET landed_cost_net_gst = 28.0 WHERE name = 'Talc Powder';
UPDATE ingredients SET landed_cost_net_gst = 1701.0 WHERE name = 'Tinogard TT';
UPDATE ingredients SET landed_cost_net_gst = 2070.0 WHERE name = 'Tinopal CBSX';
UPDATE ingredients SET landed_cost_net_gst = 350.0 WHERE name = 'Isopropyl Myristate';
UPDATE ingredients SET landed_cost_net_gst = 98.0 WHERE name = 'Light Liquid Paraffin';
UPDATE ingredients SET landed_cost_net_gst = 100.0 WHERE name = 'Galaxy CAPB';
UPDATE ingredients SET landed_cost_net_gst = 700.0 WHERE name = 'Almond Oil';
UPDATE ingredients SET landed_cost_net_gst = 3305.4 WHERE name = 'Argan Oil';
UPDATE ingredients SET landed_cost_net_gst = 1100.0 WHERE name = 'Avocado Oil';
UPDATE ingredients SET landed_cost_net_gst = 1300.0 WHERE name = 'Bakuchi Oil';
UPDATE ingredients SET landed_cost_net_gst = 5400.0 WHERE name = 'Carrot Seed Oil';
UPDATE ingredients SET landed_cost_net_gst = 149.67 WHERE name = 'Castor Oil';
UPDATE ingredients SET landed_cost_net_gst = 400.0 WHERE name = 'Coconut Oil';
UPDATE ingredients SET landed_cost_net_gst = 550.0 WHERE name = 'Olive Oil';
UPDATE ingredients SET landed_cost_net_gst = 10500.0 WHERE name = 'Patchouli Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 3300.0 WHERE name = 'Amino Acid Complex';
UPDATE ingredients SET landed_cost_net_gst = 7617.2 WHERE name = 'Beta Arbutin';
UPDATE ingredients SET landed_cost_net_gst = 2150.0 WHERE name = 'Ethyl Cellulose';
UPDATE ingredients SET landed_cost_net_gst = 635.0 WHERE name = 'HPMC';
UPDATE ingredients SET landed_cost_net_gst = 245.0 WHERE name = 'Methyl Salicylate IP';
UPDATE ingredients SET landed_cost_net_gst = 1919.15 WHERE name = 'Vitamin E';
UPDATE ingredients SET landed_cost_net_gst = 7000.0 WHERE name = 'Alizarine Purple';
UPDATE ingredients SET landed_cost_net_gst = 500.0 WHERE name = 'Xerlite Sinopia Brown';
UPDATE ingredients SET landed_cost_net_gst = 1700.0 WHERE name = 'Chlorophyll';
UPDATE ingredients SET landed_cost_net_gst = 4900.0 WHERE name = 'Koelron Brown';
UPDATE ingredients SET landed_cost_net_gst = 6200.0 WHERE name = 'Prisma Bronze';
UPDATE ingredients SET landed_cost_net_gst = 7800.0 WHERE name = 'Prism Blush Pink';
UPDATE ingredients SET landed_cost_net_gst = 6200.0 WHERE name = 'Prism Copper';
UPDATE ingredients SET landed_cost_net_gst = 7800.0 WHERE name = 'Prism Mocha';
UPDATE ingredients SET landed_cost_net_gst = 10800.0 WHERE name = 'Prism Rust Orange Glitter';
UPDATE ingredients SET landed_cost_net_gst = 7800.0 WHERE name = 'Prism Turf Green';
UPDATE ingredients SET landed_cost_net_gst = 2000.0 WHERE name = 'Solvent Yellow 18';
UPDATE ingredients SET landed_cost_net_gst = 625.0 WHERE name = 'Apricot Kernel Oil';
UPDATE ingredients SET landed_cost_net_gst = 1772.36 WHERE name = 'Basil Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1300.0 WHERE name = 'Bergamot Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 4250.0 WHERE name = 'Black Pepper Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 975.0 WHERE name = 'Black Seed Oil';
UPDATE ingredients SET landed_cost_net_gst = 1080.0 WHERE name = 'Camphor Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1194.44 WHERE name = 'Cassia Oil';
UPDATE ingredients SET landed_cost_net_gst = 842.31 WHERE name = 'Cedarwood Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 16500.0 WHERE name = 'Chamomile Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 100.0 WHERE name = 'Cinnamon Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1100.0 WHERE name = 'Eucalyptus Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 2882.01 WHERE name = 'Frankincense Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 7800.0 WHERE name = 'Geranium Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 550.0 WHERE name = 'Grape Seed Oil';
UPDATE ingredients SET landed_cost_net_gst = 2000.0 WHERE name = 'Hemp Seed Oil';
UPDATE ingredients SET landed_cost_net_gst = 2400.0 WHERE name = 'Juniper Berry Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 3066.11 WHERE name = 'Lavandin Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 7150.0 WHERE name = 'Lavender Oil';
UPDATE ingredients SET landed_cost_net_gst = 1482.46 WHERE name = 'Lemongrass Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1450.0 WHERE name = 'Lemon Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 2300.0 WHERE name = 'Lime Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 2160.0 WHERE name = 'Mandarin Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 400.0 WHERE name = 'Neem Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 4750.0 WHERE name = 'Neroli Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1685.0 WHERE name = 'Orange Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 2225.0 WHERE name = 'Palmarosa Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1225.0 WHERE name = 'Peppermint Oil';
UPDATE ingredients SET landed_cost_net_gst = 1000.0 WHERE name = 'Pine Tar Oil';
UPDATE ingredients SET landed_cost_net_gst = 120000.0 WHERE name = 'Rose Damask Absolute';
UPDATE ingredients SET landed_cost_net_gst = 3600.0 WHERE name = 'Rose Geranium Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 4100.0 WHERE name = 'Rosehip Oil';
UPDATE ingredients SET landed_cost_net_gst = 3425.0 WHERE name = 'Rosemary Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 4750.0 WHERE name = 'Sea Buckthorn Oil';
UPDATE ingredients SET landed_cost_net_gst = 1500.0 WHERE name = 'Spearmint Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 2000.0 WHERE name = 'Star Anise Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 3458.01 WHERE name = 'Tea Tree Oil';
UPDATE ingredients SET landed_cost_net_gst = 1250.0 WHERE name = 'Turmeric Leaf Oil';
UPDATE ingredients SET landed_cost_net_gst = 1125.03 WHERE name = 'Turmeric Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 4150.0 WHERE name = 'Vanilla Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 1232.76 WHERE name = 'Walnut Oil';
UPDATE ingredients SET landed_cost_net_gst = 475.0 WHERE name = 'Wheat Germ Oil';
UPDATE ingredients SET landed_cost_net_gst = 900.0 WHERE name = 'Wintergreen Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 7449.68 WHERE name = 'Ylang Ylang Essential Oil';
UPDATE ingredients SET landed_cost_net_gst = 20501.53 WHERE name = 'Songyi Mushroom Extract';
UPDATE ingredients SET landed_cost_net_gst = 900.0 WHERE name = 'Papaya Fruit Extract';
UPDATE ingredients SET landed_cost_net_gst = 134178.12 WHERE name = 'Saffron Extract';
UPDATE ingredients SET landed_cost_net_gst = 1000.27 WHERE name = 'Champa Millenium Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 950.0 WHERE name = 'Butter Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 28.53 WHERE name = 'Dark Chocolate Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 850.0 WHERE name = 'Dove Type Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1512.74 WHERE name = 'Florales Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 928.3 WHERE name = 'Fragrance AL16456-SHK';
UPDATE ingredients SET landed_cost_net_gst = 1129.8 WHERE name = 'Fragrance C1824';
UPDATE ingredients SET landed_cost_net_gst = 1069.21 WHERE name = 'Fragrance B0525';
UPDATE ingredients SET landed_cost_net_gst = 598.5 WHERE name = 'Rose NP7828 Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 527.26 WHERE name = 'Sakura Dream Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 640.0 WHERE name = 'Rose Fragrance (Fasli Gulab)';
UPDATE ingredients SET landed_cost_net_gst = 734.15 WHERE name = 'Golden Beauty Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1286.83 WHERE name = 'Green Apple Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 980.0 WHERE name = 'Jasmine Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1050.0 WHERE name = 'Kiwi Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1711.14 WHERE name = 'Lavender Fresh Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 850.0 WHERE name = 'Lemon Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1388.18 WHERE name = 'Mango Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1400.0 WHERE name = 'Saffron Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 929.37 WHERE name = 'Orange Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1521.03 WHERE name = 'Oudh Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 900.0 WHERE name = 'Papaya Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1150.0 WHERE name = 'Peach Nectar Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 775.0 WHERE name = 'Pears Type Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 949.9 WHERE name = 'Pine Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 3000.0 WHERE name = 'Roses of Heaven Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 568.77 WHERE name = 'Sandalwood Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 1766.1 WHERE name = 'Sandelia K Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 650.0 WHERE name = 'Turmeric Fragrance';
UPDATE ingredients SET landed_cost_net_gst = 185.0 WHERE name = 'Galaxy SN960 SF';
UPDATE ingredients SET landed_cost_net_gst = 260.0 WHERE name = 'Galfusion Gentle Care-SB';
UPDATE ingredients SET landed_cost_net_gst = 325.0 WHERE name = 'Ipure-SFMP7';
UPDATE ingredients SET landed_cost_net_gst = 89.83 WHERE name = 'Soap Noodles 73%';
UPDATE ingredients SET landed_cost_net_gst = 102.0 WHERE name = 'Soap Noodles 80:20';
UPDATE ingredients SET landed_cost_net_gst = 92.67 WHERE name = 'Sinar Mas Soap Noodles';
COMMIT;
