BEGIN TRANSACTION;

-- PRISMA BRONZE
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Prisma Bronze', 'Mica (CI 77019), Iron Oxides (CI 77491, CI 77492, CI 77499)', '12001-26-2', 6, 6200.00, 'in_stock', 'kg', 0.1, 1.0, 'Store in cool, dry place. Keep container tightly closed.', 36, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Prisma Bronze'), '310-127-6', '77019', 'Mica + Fe2O3', 1, 1, 'Cosmetic grade. Safe for soap and cosmetics. Not for lip or eye area unless certified.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Prisma Bronze'), 'Bronze metallic shimmer powder', 'Insoluble in water. Disperses in oils.', 'Mix 1 tsp with 1 tbsp oil before adding to soap at trace. Use 0.1-1% for desired intensity. Pearlescent finish.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Prisma Bronze'), 'CP soap, MP soap, bath bombs, lotions, cosmetics', 'Metallic bronze shimmer, pearlescent effect, stable in high pH, non-bleeding');

-- PRISM BLUSH PINK
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Prism Blush Pink', 'Mica (CI 77019), Titanium Dioxide (CI 77891), Iron Oxides (CI 77491)', '12001-26-2', 6, 7800.00, 'in_stock', 'kg', 0.1, 1.0, 'Store in cool, dry place. Keep container tightly closed.', 36, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Blush Pink'), '310-127-6', '77019', 'Mica + TiO2 + Fe2O3', 1, 1, 'Cosmetic grade. Safe for soap and cosmetics. Check certification for lip/eye use.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Blush Pink'), 'Soft pink shimmer powder', 'Insoluble in water. Disperses in oils.', 'Mix 1 tsp with 1 tbsp oil before adding to soap at trace. Use 0.1-1% for desired intensity. Pearlescent finish.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Blush Pink'), 'CP soap, MP soap, bath bombs, lotions, blush, cosmetics', 'Soft pink shimmer, pearlescent effect, stable in high pH, non-bleeding, feminine tones');

-- PRISM COPPER
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Prism Copper', 'Mica (CI 77019), Iron Oxides (CI 77491, CI 77492)', '12001-26-2', 6, 6200.00, 'in_stock', 'kg', 0.1, 1.0, 'Store in cool, dry place. Keep container tightly closed.', 36, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Copper'), '310-127-6', '77019', 'Mica + Fe2O3', 1, 1, 'Cosmetic grade. Safe for soap and cosmetics. Not for lip or eye area unless certified.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Copper'), 'Copper metallic shimmer powder', 'Insoluble in water. Disperses in oils.', 'Mix 1 tsp with 1 tbsp oil before adding to soap at trace. Use 0.1-1% for desired intensity. Pearlescent finish.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Copper'), 'CP soap, MP soap, bath bombs, lotions, cosmetics', 'Warm copper shimmer, metallic effect, stable in high pH, non-bleeding');

-- PRISM MOCHA
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Prism Mocha', 'Mica (CI 77019), Iron Oxides (CI 77491, CI 77492, CI 77499)', '12001-26-2', 6, 7800.00, 'in_stock', 'kg', 0.1, 1.0, 'Store in cool, dry place. Keep container tightly closed.', 36, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Mocha'), '310-127-6', '77019', 'Mica + Fe2O3', 1, 1, 'Cosmetic grade. Safe for soap and cosmetics. Not for lip or eye area unless certified.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Mocha'), 'Rich brown shimmer powder with warm undertones', 'Insoluble in water. Disperses in oils.', 'Mix 1 tsp with 1 tbsp oil before adding to soap at trace. Use 0.1-1% for desired intensity. Pearlescent finish.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Mocha'), 'CP soap, MP soap, bath bombs, lotions, cosmetics', 'Warm brown shimmer, coffee tones, pearlescent effect, stable in high pH, non-bleeding');

-- PRISM RUST ORANGE GLITTER
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Prism Rust Orange Glitter', 'Mica (CI 77019), Iron Oxides (CI 77491, CI 77492)', '12001-26-2', 6, 10800.00, 'in_stock', 'kg', 0.1, 1.0, 'Store in cool, dry place. Keep container tightly closed.', 36, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Rust Orange Glitter'), '310-127-6', '77019', 'Mica + Fe2O3', 1, 1, 'Cosmetic grade. Safe for soap and cosmetics. Contains glitter particles.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Rust Orange Glitter'), 'Rust orange glitter with sparkle particles', 'Insoluble in water. Disperses in oils.', 'Mix 1 tsp with 1 tbsp oil before adding to soap at trace. Use 0.1-1%. Larger particle size for glitter effect.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Rust Orange Glitter'), 'CP soap, MP soap, bath bombs, autumn-themed products', 'Bold rust orange sparkle, glitter effect, autumn tones, eye-catching shimmer');

-- PRISM TURF GREEN
INSERT INTO ingredients (name, inci_name, cas_number, category_id, landed_cost_net_gst, stock_status, unit_of_measure, usage_rate_min, usage_rate_max, storage_conditions, shelf_life_months, created_at, updated_at) VALUES ('Prism Turf Green', 'Mica (CI 77019), Chromium Oxide Green (CI 77288)', '12001-26-2', 6, 7800.00, 'in_stock', 'kg', 0.1, 1.0, 'Store in cool, dry place. Keep container tightly closed.', 36, datetime('now'), datetime('now'));
INSERT INTO ingredient_regulatory (ingredient_id, einecs, cosing_ref, chemical_formula, us_approved, eu_approved, safety_notes) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Turf Green'), '310-127-6', '77019', 'Mica + Cr2O3', 1, 1, 'Cosmetic grade. Safe for soap and cosmetics. Not for lip area.');
INSERT INTO ingredient_properties (ingredient_id, appearance, solubility, formulation_notes, sap_value, iodine_value, ins_value, hardness_coefficient, lather_coefficient) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Turf Green'), 'Rich green shimmer powder', 'Insoluble in water. Disperses in oils.', 'Mix 1 tsp with 1 tbsp oil before adding to soap at trace. Use 0.1-1% for desired intensity. Pearlescent finish.', NULL, NULL, NULL, 0, 0);
INSERT INTO ingredient_marketing (ingredient_id, applications, benefits) VALUES ((SELECT id FROM ingredients WHERE name = 'Prism Turf Green'), 'CP soap, MP soap, bath bombs, nature-themed products', 'Rich green shimmer, nature tones, pearlescent effect, stable in high pH, non-bleeding');

COMMIT;
